# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: RedSmokes
main: com.bss.inc.redsmokes.main.RedSmokes
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${full.version}
description: Provides an essential, core set of commands for Bukkit to turn it into a drug house :).
softdepend: [Vault, LuckPerms]
authors: [RedstonedLife, xeryka]
api-version: "1.13"
commands:
  redsmokes:
    description: Reloads RedSmokes
    usage: /<command>
    aliases: [redsmokes,resm,rsm,res]
  balance:
    description: States the current balance of a player.
    usage: /<command> [player]
    aliases: [bal,rbal,rbalance,money,rmoney]                                                                           # Added in v1.0.1.27-dev+1380-98d201b
  balancetop:
    description: Gets the top balance values.
    usage: /<command> [page]
    aliases: [balancetop,baltop]                                                                                        # Added in v1.0.1.47-dev+1441-0f2d0e6

permissions:
  redsmokes.*:
    default: op
    description: Give players with op everything by default