# This determines the command prefix when there are conflicts (/name:home, /name:help, etc.)
name: RedSmokes
main: com.bss.inc.redsmokes.main.RedSmokes
# Note to developers: This next line cannot change, or the automatic versioning system will break.
version: ${full.version}
description: Provides an essential, core set of commands for Bukkit to turn it into a drug house :).
softdepend: [Vault, LuckPerms]
authors: [RedstonedLife, xeryka]
api-version: "1.13"
commands:
  redsmokes:
    description: Reloads RedSmokes
    usage: /<command>
    aliases: [rredsmokes,rrsm,rresm,rres]